redirectsOrigin = "config"
headers = []

[functions]

[functions."*"]

[[plugins]]
origin = "default"
package = "@netlify/angular-runtime"

[plugins.inputs]

[build]
publish = "C:\\Users\\gajya\\Academic project subimission\\frontend\\dist\\frontend\\browser"
publishOrigin = "config"
commandOrigin = "config"
base = "C:\\Users\\gajya\\Academic project subimission\\frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]